"""update

Revision ID: 9ed5f2d648b6
Revises: 56d3849a11d5
Create Date: 2018-08-05 22:32:05.939034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ed5f2d648b6'
down_revision = '56d3849a11d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sa.String(length=11), nullable=True))
    op.add_column('user', sa.Column('real_name', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('work_years', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'work_years')
    op.drop_column('user', 'real_name')
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###
